geometry_msgs/Point point  # Målpunkt (klienten sender dette)

---
bool success               # Status (serveren svarer med dette)
string result_message      # Valgfri melding fra serveren

---
float32 progress           # Tilbakemelding underveis (serveren sender dette)